2024-03-09 22:55:00,724 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-09 22:55:00,724 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Configure stats pid to 17097
2024-03-09 22:55:00,724 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Loading settings from /Users/sunayana/.config/wandb/settings
2024-03-09 22:55:00,724 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Loading settings from /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/settings
2024-03-09 22:55:00,724 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-09 22:55:00,724 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-09 22:55:00,724 INFO    MainThread:17097 [wandb_init.py:_log_setup():526] Logging user logs to /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/run-20240309_225500-gw2vhkxa/logs/debug.log
2024-03-09 22:55:00,724 INFO    MainThread:17097 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/run-20240309_225500-gw2vhkxa/logs/debug-internal.log
2024-03-09 22:55:00,725 INFO    MainThread:17097 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x17ee0dca0>
2024-03-09 22:55:00,725 INFO    MainThread:17097 [wandb_init.py:init():566] calling init triggers
2024-03-09 22:55:00,725 INFO    MainThread:17097 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-09 22:55:00,725 INFO    MainThread:17097 [wandb_init.py:init():616] starting backend
2024-03-09 22:55:00,725 INFO    MainThread:17097 [wandb_init.py:init():620] setting up manager
2024-03-09 22:55:00,727 INFO    MainThread:17097 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-03-09 22:55:00,728 INFO    MainThread:17097 [wandb_init.py:init():628] backend started and connected
2024-03-09 22:55:00,736 INFO    MainThread:17097 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-09 22:55:00,737 INFO    MainThread:17097 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-09 22:55:00,737 INFO    MainThread:17097 [wandb_init.py:init():720] updated telemetry
2024-03-09 22:55:00,763 INFO    MainThread:17097 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-09 22:55:01,999 ERROR   MainThread:17097 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-09 22:55:02,215 ERROR   MainThread:17097 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/sunayana/anaconda3/envs/newenvt/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/sunayana/anaconda3/envs/newenvt/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Configure stats pid to 17097
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Loading settings from /Users/sunayana/.config/wandb/settings
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Loading settings from /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/settings
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_init.py:_log_setup():526] Logging user logs to /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/run-20240309_225551-j4fqoot0/logs/debug.log
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/sunayana/Documents/GitHub/CV/assignment2/wandb/run-20240309_225551-j4fqoot0/logs/debug-internal.log
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_init.py:init():566] calling init triggers
2024-03-09 22:55:51,544 INFO    MainThread:17097 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-09 22:55:51,545 INFO    MainThread:17097 [wandb_init.py:init():616] starting backend
2024-03-09 22:55:51,545 INFO    MainThread:17097 [wandb_init.py:init():620] setting up manager
2024-03-09 22:55:51,547 INFO    MainThread:17097 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-03-09 22:55:51,547 INFO    MainThread:17097 [wandb_init.py:init():628] backend started and connected
2024-03-09 22:55:51,555 INFO    MainThread:17097 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-09 22:55:51,555 INFO    MainThread:17097 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-09 22:55:51,555 INFO    MainThread:17097 [wandb_init.py:init():720] updated telemetry
2024-03-09 22:55:51,581 INFO    MainThread:17097 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-09 22:55:52,741 INFO    MainThread:17097 [wandb_run.py:_on_init():2262] communicating current version
2024-03-09 22:56:22,833 INFO    MainThread:17097 [wandb_init.py:init():804] starting run threads in backend
2024-03-09 22:56:27,641 WARNING MsgRouterThr:17097 [router.py:message_loop():77] message_loop has been closed
2024-03-09 22:56:52,954 INFO    MainThread:17097 [wandb_run.py:_console_start():2241] atexit reg
2024-03-09 22:56:52,955 INFO    MainThread:17097 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-09 22:56:52,955 INFO    MainThread:17097 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-09 22:56:52,955 INFO    MainThread:17097 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-09 22:56:52,955 INFO    MainThread:17097 [wandb_init.py:init():847] run started, returning control to user process
2024-03-09 22:56:52,956 INFO    MainThread:17097 [wandb_watch.py:watch():51] Watching
2024-03-09 22:59:42,039 INFO    MainThread:17097 [wandb_run.py:_finish():1970] finishing run sunayana981/vit_mnist_classification/j4fqoot0
2024-03-09 22:59:42,042 INFO    MainThread:17097 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-09 22:59:42,042 INFO    MainThread:17097 [wandb_run.py:_restore():2193] restore
2024-03-09 22:59:42,042 INFO    MainThread:17097 [wandb_run.py:_restore():2199] restore done
